== Testimonies Concerning Richard Davies.

[.blurb]
=== The Testimony and Account of George Whitehead, Concerning Richard Davies, and His Ministry.

In a true and living remembrance of this our dear brother,
ancient and faithful servant and minister of Jesus Christ, Richard Davies,
and of that dear and brotherly love which remained between us,
and which he had to all faithful Friends and brethren in Christ;
I am concerned to give this brief testimony in commemoration of his life,
and faithful ministry.

He was not only a professor of the name, power,
and spirit of our blessed Lord and Saviour Jesus Christ,
but also made a partaker of Christ, in spirit, life, and conversation: a plain, meek,
and humble man of integrity; a man fearing God, and hating iniquity;
a man sanctified by the Holy Spirit,
unto unfeigned and constant love of his brethren in Christ; a man sound in faith,
in patience, and charity; of a sound mind and judgment,
being endued with the spirit of love.
He was a preacher of Christ and his righteousness,
in his conversation as well as in doctrine and ministry,
wherein he was exemplary to the believers.
He was given up to serve the truth and Friends; and being of a tender spirit,
did truly sympathize with the sufferers for the same,
and used his industrious endeavours for their relief,
where he could have an interest or place with such as had power.

His testimony and ministry were evangelical, plain, and sound;
not in words of man`'s wisdom,
but in the demonstration and plain evidence of the holy Spirit and power of Christ,
being a minister of the spirit, and of the New Testament; the new covenant dispensation,
which stands not in legal shadows, types, outward signs or figures,
but in the gospel life and substance, even in Christ Jesus; in whom all the shadows,
and dispensations thereof, are ended.

And this our dear brother having travelled
through and beyond those outward dispensations,
shadows, and veils; and understanding their cessation, removal, and end,
in and by Christ Jesus, his sufferings and death;
and more especially by his inward and spiritual appearance, dispensation,
and work in his heart and soul;
whereby he was made sensible of the power of Christ`'s resurrection,
as being one risen with him; by the brightness and glory of whose day,
the shadows naturally vanish and flee away;
as this faithful minister of Christ was witness, with many more of his brethren,
who were and are partakers of the inward and
spiritual revelation of the mystery of Christ,
and of the glory of his day.

And as this gospel minister did see and partake of the enduring substance,
and end of all vanishing shadows and carnal ordinances, he well knew,
that neither John`'s baptism with water, nor any outward washings therewith,
though once commanded, could ever sanctify, or wash the inside from sin and pollution,
or sprinkle and purify the conscience, or make a true Christian;
much less can sprinkling infants, which God never commanded;
but Christ`'s spiritual baptism, and washing of regeneration by the water of life,
which is the one baptism i. e. the baptism of the Spirit, is the only saving baptism,
as our said deceased friend hath testified, according to Holy Scripture.

He also likewise testified,
that outward bread and wine cannot feed nor nourish the immortal soul, or inward man,
any more than the legal passover; but only the body or outward man: but Christ,
the living bread, the bread of life, which comes down from heaven;
and the cup of blessing, which he gives to his spiritual communicants:
he being that spiritual meat and drink, which all his spiritual Israel partake of,
in this his gospel day,
to their great refreshment and comfort in the spiritual communion,
and comfortable fellowship of his Holy Spirit.
To this our dear friend`'s ministry tended to bring people;
that they might not rest in lifeless shadows,
but come to know and inherit eternal life and substance, in Christ Jesus,
which all that truly love him shall partake of and possess.

And I am fully persuaded,
that as this our dear and well beloved friend and brother lived and died in the faith,
in our blessed Lord and Saviour Jesus Christ,
and in true union and communion with his church and people here on earth;
so I believe he is eternally blessed, and at rest in his heavenly kingdom;
where all the faithful in Christ shall meet in the great and
general assembly of Christ`'s triumphant church,
and enjoy glorious and everlasting communion in the heavenly kingdom of glory and peace;
which shall be the blessed estate and inheritance of all,
who continue faithful in true love and unity, in the grace of God, while here on earth,
unto the end of their days.

[.signed-section-signature]
George Whitehead.

[.signed-section-context-close]
London, the 10th of the Twelfth month, 1709.

[.blurb]
=== A Short Testimony Concerning My Dear and Loving Father, Richard Davies.

I can truly say, he was a dear and tender father to me in my young years;
and as I grew up, I had a sense of his great love and care over me;
and it seized my heart so that I often prayed to God,
that he would keep me from offending so good a father.
And when I was capable of travelling with him, he usually took me along with him,
in his journeys to London and elsewhere;
many were the good opportunities that we had in travelling together,
and visiting Friends at their meetings.

And as his care was to me, so was it over mine also, which makes our loss the greater;
but I am satisfied it is his great gain.
How often and fervently would he pray to the Almighty,
that his children might become the children of the Lord,
and that he might keep us from the allurements and defilements of this wicked world;
and we hope the Lord will answer his petitions on our behalf.

My dear father was serviceable to most sorts of people, rich and poor,
in the country where he lived, and in other places.
He was ready to give his advice and counsel freely,
both in things relating to the law and the gospel;
he had much place and interest with several great persons,
and what he requested of them was generally granted him.
And I may say it to the praise of the Lord,
he was well respected by most sorts of people, and a loss of him is known amongst them.

He was very ready to serve the widow and fatherless, in what lay in his power;
and many were his labours and travels of love: but now he is ceased from them all,
and I question not but he has gone to his eternal rest with God forever.
It is my desire, that we may prize the great goodness and loving kindness of the Lord,
in sparing him so long to us, for he had been but a weakly man these late years.

About the tenth month, 1688, my dear father was very sick and weak,
so that most that saw him thought he would not recover; but the Lord,
in his tender mercy, so ordered that our dear friends Robert Barrow and Robert Flaydock,
came into these parts to visit Friends; and they came to our house at Welch-Pool,
and had a meeting there; and as they were parting with my father,
they had it in their hearts to pray, and they earnestly interceded with the Lord,
That it might stand good with his will, to spare him again unto us;
for we were then a sorrowful family.
Afterwards, I remember very well, Robert Barrow spoke, and said to my father,
"`Dear Richard, thou art a very weakly man in the sight of those that see thee,
and not likely to live many hours, as to the natural man`'s thinking;
but the Lord has given it me at this time to believe,
I shall see thee at our next yearly meeting at London.`"
When I heard these words it was joyful news to me, and it proved very true;
the Lord in his wonderful mercy and loving kindness, restored him to his health,
and next spring he went to the yearly meeting at London, where also Robert Barrow was,
and glad to see my father there.
This was all the Lord`'s doings, and his works they are marvellous in our eyes.

Much might be said; but my desire is, that as our ancient friends,
fathers and mothers in Israel, have borne the burden in the heat of the day,
through many tribulations and afflictions, and now have rested from their labours,
and their works follow them, and their memorial is blessed forevermore;
so we also who are left, may walk in the footsteps of the flock,
and tread in the path they have trodden in.
It is, as to the outward, an easy way now, to what our ancients had,
but the adversary of our immortal souls is the same, he is unwearied;
therefore we ought to be very careful, and double our diligence,
to be sober and watchful, and cry incessantly to the Lord God of our fathers,
that he may be our God,
and enable us to walk worthy of all his mercies and blessings every way,
for they are many.

Now I shall give some account of my dear father`'s departure.
He was taken ill on the sixth-day of the week,
being the 19th of the first month 1707-8. On first-day following,
he sent for some Friends of Dolobran meeting, and several of them came to him,
and had a meeting with him in his bed-chamber; he desired Friends to pray to the Lord,
That he might have an easy passage; adding, "`That the fervent prayers of the righteous,
the Lord would have a regard unto.`"
And his time being come, he departed this life, as it were in a sleep,
it being about the ninth hour in the forenoon, the 22nd of the first month, 1707-8,
On the 25th following,
his body was accompanied by a considerable number of Friends and people,
to the burying place, near his own house at Cloddiecochion, and there decently interred.

And now it is my desire, that all of us who have had such good examples, by our parents,
may follow them in purity and holiness;
so that we may be such good patterns to our offspring, that when we lay down our heads,
and leave this natural life,
they may have cause to praise and glorify the Lord on our account, as many of us can say,
we have had for our worthy parents that are gone.
If we continue in well-doing, and in the fear of the Lord,
there is no question but we shall die in his favour,
which I desire may be the lot of the whole heritage of God.

[.signed-section-signature]
Tace Endon.

[.signed-section-context-close]
Cloddiecochion, the 27th of the First month, 1708.

[.blurb]
=== A Testimony from friends and brethren of the Quarterly meeting for Montgomeryshire, Shropshire, and Merionethshire, held at Dolobran in Montgomeryshire, the 25th of the Eleventh month, 1708, concerning our ancient, honourable friend and elder, Richard Davies.

He was one of the first of Friends in these parts,
who received the blessed truth in the love of it;
and he laboured much in the morning and heat of the day.

He and his wife were very hearty, loving, and ready to entertain Friends,
their hearts and house being very open in that respect;
and they were very helpful and serviceable to Friends in this country,
who were prisoners on truth`'s account in Welch-Pool, the place where they then lived,
when there were but few other Friends of ability to assist them;
until the Lord raised up several eminent instruments in these parts,
who were very serviceable with them.

Our said friend was wise and prudent.
He had a good understanding and capacity; a man of great experience;
and was very willing to advise and counsel any in things relating to the gospel,
and also to outward affairs.

And as he was discreet in his conduct among men,
the Lord gave him great place and favour with several persons of note,
with whom he had often good service for truth and Friends.

The Lord blessed him with a good gift in the ministry,
and he was made an able minister of the gospel; sound in judgment,
and well received by most people who heard him.

He travelled in divers parts on truth`'s service, especially in his younger years;
and had good service in many places, both at home and abroad.
He was often at London, where he was well esteemed by many of our elders and brethren.

He lived to a good old age, and was favoured with a short sickness at last.
Some of us were with him the day before his departure;
he seemed sensible that his end was near approaching,
and appeared as one that was waiting for the same.
He departed this life the 22nd of the first month, 1707-8, in the 73rd year of his age;
and we believe he is at rest with the Lord,
together with many more of the faithful followers of the Lamb.

We shall not enlarge much further, but refer to the foregoing account of his labours,
travels and services for truth and Friends on several occasions,
which contains a general relation of the most remarkable occurrences of his life,
which was written by himself not long before his decease.

And we earnestly desire that all, who make profession of the glorious truth with us,
may really know a "`working out of their salvation with fear and
trembling;`" and that they may faithfully improve their talents,
and follow the examples of the faithful elders and servants of
the Lord in all things wherein they followed Christ,
that we may give our account at last with joy,
and receive an eternal reward with the children of the Lord,
when time to us will be no more.

"`Blessed are the dead which die in the Lord, from henceforth; yea, saith the spirit,
that they may rest from their labours, and their works do follow them.`" Rev. 14:13.

[.signed-section-closing]
Signed on behalf of the said meeting, by us:

[.signed-section-signature]
Charles Lloyd, Owen Roberts, Rowland Owen,
William Reynolds, Robert Vaughan, Humphrey Owen, Robert Griffithes, Jacob Endon,
John Simpson, Owen Lewis, Thomas Cadwalader, Richard Lewis, John Richards, Ellis Lewis,
William Osborn, Thomas Oliver, Joseph Davies, Richard Evans, Edward Ellis, William Soley,
Richard Bembow, Griffith Owen, Richard Ruff, John Roberts, Julius Palmer, John Kelsall,
Amos Davies.

[.blurb]
=== The Testimony of Rowland Owen, Concerning His Dear Friend Richard Davies.

A weighty consideration came upon my mind,
how the Almighty in his unspeakable and unsearchable wisdom,
who discerneth the states and conditions of the sons and daughters of men,
maketh choice of some, cmd calleth them from among their neighbours and relations,
to be serviceable unto him: amongst whom our dear friend Richard Davies was called early,
in the day of God`'s visitation, to serve him; and he gave up in obedience to the Lord,
and took up the cross in a time of great persecution.

The Lord made him willing and obedient, in those days,
to go abroad with a public testimony for the truth,
and moved him to come to our country of Merionethshire,
when some of us were young in years;
and it pleased the Lord to make him instrumental to bring glad tidings to our ears,
and his testimony was sweet and comfortable,
to the edifying and tendering of our hearts and souls; many of us loved him exceedingly,
and that love remained between him and us till the end of his days.
He was tender and careful of us,
and a nourisher and strengthener of some of us in our spiritual exercises,
and was ready to assist the weak and feeble, and willing to give a helping hand,
counsel and admonition to Friends, and others, that had any desires to serve the Lord.

O the wonderful wisdom and love of God! who called him, and many others in those days,
and prepared and qualified them for the great work they had to do,
and strengthened them to tread the way before us, that were weak and feeble.
How strong and valiant instruments did the Lord God
prepare to begin to strike at the great image of pride,
haughtiness, etc. that was then, and yet is in the world!
Indeed their memorial is worthy to be recorded,
that ages yet to come might see what the Lord hath done for his faithful ones,
who gave up their lives, and all they had, on truth`'s account.

I was acquainted with our said friend about forty years, and I can say of a truth,
that his service was great in the church of Christ, especially in times of persecution;
he having much interest with the magistrates, and them in authority in those days.
His house was very open to entertain Friends, to the utmost of his ability;
and the Lord blessed him.

The Lord, out of his treasure of grace,
eminently endued him to bear a sound and seasonable testimony,
when great assemblies were gathered together;
and he had a skillful hand to administer unto them the way of truth,
and to open it to their understandings; which many times gave them great satisfaction,
and they were made to speak well of truth and its followers.
O the deep sense that remains upon me,
of the great want we have of the service of such as he was!
The Lord who in his mercy qualified and fitted him,
is able to prepare and raise up other faithful labourers.

It affects me, when I remember his gravity, his manly presence, and lovely countenance,
especially when he stood up in a meeting.
Now he hath finished his course, and I believe, hath done his day`'s work,
and is gone to his eternal rest.

Much more might be said on his behalf, but I desire that none may mistake me,
I am not giving honour to man, that is but dust and ashes;
but that all might see how Almighty God doth bestow his
spiritual gifts upon those of whom he requireth service.
And it is our duty, as our Saviour Jesus Christ advised his beloved disciples,
to pray to the Lord of the harvest, which harvest is great,
that he would send forth more faithful labourers into his harvest,
that mankind might be gathered into the inward possession and substance of Christianity,
which many outwardly profess; that the God of all our mercies,
and his beloved Son Jesus Christ, may have all the glory and thanksgiving,
to whom it belongs, not only now, but henceforth and forever more.
Amen.

[.signed-section-signature]
Rowland Owen.
